baseURL = "https://walkloud.github.io/hugo-texademic/"
enableGitInfo = false # true: page modification date set by last git commit
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
rssLimit = 10
title = "tab-title"

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"
presenter = "presenter"

[params]
    theme="blue-grey"
    dateFormat = "2 January 2006"
    front_news = 5

    title="<GROUP_NAME> Collaboration"
    author = "Andr√© Walker-Loud"
    description = "TeXaDemic - A LaTeX-style hugo theme for personal and group academic sites"
    footnote = """
    Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
    Theme <a class=link href=https://github.com/walkloud/hugo-texademic target=_blank rel=noopener>TeXaDemic</a>
    """
    customCSS = []
    customJS = []
    emphasisWithDots = true
    toc = true
    rootFontSize = "105%"
    math = true
    enableDuckDuckGoSearchBox = true
    numberedSubtitles = true
    default_portrait = "images/anonymous_person.png"
    memberClass = false

[params.buymeacoffee]
code = """
<script data-name="BMC-Widget" 
    data-cfasync="true" 
    src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
    data-id="loudwalker" 
    data-description="Like what I do? Buy me a coffee!" 
    data-message="" 
    data-color="#d79921" 
    data-position="Right" 
    data-x_margin="18" 
    data-y_margin="18"
    crossorigin="anonymous">
</script>
"""

[params.sharingbuttons]
  facebook = true
  x = true
  email = true
  linkedin = true
  reddit = true
  whatsapp = true
  hackernews = true
  telegram = true

[[menus.main]]
    name = '<GROUP_NAME>'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[[menus.main]]
    name = 'News'
    pageRef = '/news'
    weight = 30
[[menus.main]]
    name = 'Members'
    pageRef = '/members'
    weight = 40
# Member sub menus
[[menus.main]]
    name = 'Seniors'
    parent = "Members"
    pageRef = '/members/seniors'
    weight = 1
[[menus.main]]
    name = 'Postdocs'
    parent = "Members"
    pageRef = '/members/postdocs'
    weight = 2
[[menus.main]]
    name = 'Grad Students'
    parent = "Members"
    pageRef = '/members/gradstudents'
    weight = 3
[[menus.main]]
    name = 'Under Grads'
    parent = "Members"
    pageRef = '/members/undergrads'
    weight = 4
[[menus.main]]
    name = 'Former Members'
    parent = "Members"
    pageRef = '/members/former'
    weight = 5

# back to main menu
[[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 50
[[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 60
[[menus.main]]
    name = 'Software'
    pageRef = '/software'
    weight = 70
